### ISSUE TITLE
No configuration setting found for key 'coreference'

### ISSUE THREAD

**Issue by hate5six** [Lambda-3/Graphene#14]
Trying to run a very basic test of Graphene but I run into an error with a missing key. Do I need to define a .conf file to pass into ConfigFactory.load()? If so, how is it defined? Clearer documentation would be immensely helpful for using this API.

> Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'coreference'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
        at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:264)
        at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:270)
        at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:37)
        at org.lambda3.graphene.core.Graphene.<init>(Graphene.java:61)
        at DJRE.main(DJRE.java:8)

```
import org.lambda3.graphene.core.Graphene;
import com.typesafe.config.Config;
import com.typesafe.config.ConfigFactory;
public class DJRE {
    public static void main(String[] args){
        Config config = ConfigFactory.load();
        Graphene graphene = new Graphene(config);
    }
}
```

**Comment by mithrial** [comment]
You have to define the URL to PyCobalt (the coreference service) somewhere.
You can either to that with VM parameters when running:
`-Dgraphene.coreference.url="http://localhost:5128"` or better, you create the file `src/main/resources/application.conf` with at least the following content:

```HOCON
graphene {
  coreference {
    url = "http://localhost:5128"
  }
}
```

**Comment by hate5six** [comment]
Getting a similar issue with the undefined key `text_path`. What should that be set to?

**Comment by mithrial** [comment]
Thank you for reporting this issue. I renamed the config files to `reference.conf` (resp. `application.conf`), so that they adhere to Typesafe's naming convention.
You have to reinstall (`mvn install -DskipTests`) before using, of course.
