### ISSUE TITLE
graphene.conf not found

### ISSUE THREAD

**Issue by wnunderwood** [Lambda-3/Graphene#2]
I receive an error after following the setup instructions and executing docker-compose up.

```
~/Graphene# docker-compose up
Creating network "graphene_default" with the default driver
Building graphene
Step 1/6 : FROM openjdk:8-jre
8-jre: Pulling from library/openjdk
6d827a3ef358: Pull complete
2726297beaf1: Pull complete
d6e483851652: Pull complete
ef624abeb7b8: Pull complete
0e108ce2208d: Pull complete
6a77bcb48281: Pull complete
016fd08a71c8: Pull complete
Digest: sha256:444f7f4a22159fdfd891ba6326523bcb20c11c1d0c12826c2cb21468e5fb5294
Status: Downloaded newer image for openjdk:8-jre
 ---> b8ce7cab8ed3
Step 2/6 : WORKDIR /usr/share/graphene
 ---> 60b2aeb30c8e
Removing intermediate container 952581b1d542
Step 3/6 : ENV LANG "en_US.UTF-8" TZ "Europe/Berlin"
 ---> Running in 4bad35d5a000
 ---> 5d77859e86c5
Removing intermediate container 4bad35d5a000
Step 4/6 : EXPOSE 8080
 ---> Running in a5e6e4cdb082
 ---> ee6a91cc0a98
Removing intermediate container a5e6e4cdb082
Step 5/6 : ADD graphene-server/target/graphene-server-1.0.1-dist/ .
 ---> 5ed095efa77e
Removing intermediate container 7879dcd8477a
Step 6/6 : CMD bin/start.sh
 ---> Running in c8feb4b57d8a
 ---> 5ed9fa6b85e0
Removing intermediate container c8feb4b57d8a
Successfully built 5ed9fa6b85e0
WARNING: Image for service graphene was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating graphene_corenlp_1
Creating graphene_coreference_1
Creating graphene_graphene_1
Attaching to graphene_corenlp_1, graphene_coreference_1, graphene_graphene_1
corenlp_1      | Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLPServer
coreference_1  | [uWSGI] getting INI configuration from uwsgi.ini
coreference_1  | *** Starting uWSGI 2.0.14 (64bit) on [Wed Apr 19 16:19:44 2017] ***
coreference_1  | compiled with version: 4.9.2 on 11 April 2017 17:20:20
coreference_1  | os: Linux-4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017
coreference_1  | nodename: 513cd09209b8
coreference_1  | machine: x86_64
coreference_1  | clock source: unix
coreference_1  | pcre jit disabled
coreference_1  | detected number of CPU cores: 2
coreference_1  | current working directory: /app
coreference_1  | detected binary path: /usr/local/bin/uwsgi
coreference_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
coreference_1  | your memory page size is 4096 bytes
coreference_1  |  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers ***
coreference_1  | detected max file descriptor number: 1048576
coreference_1  | lock engine: pthread robust mutexes
coreference_1  | thunder lock: disabled (you can enable it with --thunder-lock)
coreference_1  | uwsgi socket 0 bound to TCP address 0.0.0.0:5128 fd 3
coreference_1  | Python version: 3.6.0 (default, Feb 28 2017, 22:20:46)  [GCC 4.9.2]
coreference_1  | Python main interpreter initialized at 0x2390760
coreference_1  | python threads support enabled
coreference_1  | your server socket listen backlog is limited to 100 connections
coreference_1  | your mercy for graceful operations on workers is 60 seconds
graphene_corenlp_1 exited with code 1
coreference_1  | mapped 363840 bytes (355 KB) for 4 cores
coreference_1  | *** Operational MODE: preforking ***
coreference_1  | mounting service.py on /app
graphene_1     | 18:19:44,728 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [/usr/share/graphene/conf/logback.xml]
graphene_1     | 18:19:44,728 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
graphene_1     | 18:19:44,728 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
graphene_1     | 18:19:44,728 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/usr/share/graphene/lib/graphene-core-1.0.1.jar!/logback.xml]
graphene_1     | 18:19:44,728 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
graphene_1     | 18:19:44,729 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/share/graphene/lib/discourse-simplification-5.0.0.jar!/logback.xml]
graphene_1     | 18:19:44,729 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/share/graphene/lib/sentence-simplification-5.0.0.jar!/logback.xml]
graphene_1     | 18:19:44,729 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/share/graphene/lib/graphene-core-1.0.1.jar!/logback.xml]
graphene_1     | 18:19:44,729 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/usr/share/graphene/lib/srlie_2.10-1.0.3.jar!/logback.xml]
graphene_1     | 18:19:44,759 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@4973813a - URL [jar:file:/usr/share/graphene/lib/graphene-core-1.0.1.jar!/logback.xml] is not of type file
graphene_1     | 18:19:44,887 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
graphene_1     | 18:19:44,895 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
graphene_1     | 18:19:44,897 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
graphene_1     | 18:19:44,904 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
graphene_1     | 18:19:44,973 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
graphene_1     | 18:19:44,976 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
graphene_1     | 18:19:44,983 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@6321e813 - Will use zip compression
graphene_1     | 18:19:44,988 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
graphene_1     | 18:19:44,989 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: logs/graphene_core.log
graphene_1     | 18:19:44,989 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [logs/graphene_core.log]
graphene_1     | 18:19:44,991 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
graphene_1     | 18:19:44,991 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
graphene_1     | 18:19:44,992 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.lambda3.graphene.core] to DEBUG
graphene_1     | 18:19:44,992 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.lambda3.graphene.core] to true
graphene_1     | 18:19:44,992 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[org.lambda3.graphene.core]
graphene_1     | 18:19:44,992 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
graphene_1     | 18:19:44,992 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@79be0360 - Registering current configuration as safe fallback point
graphene_1     |
coreference_1  | WSGI app 0 (mountpoint='/app') ready in 1 seconds on interpreter 0x2390760 pid: 1 (default app)
coreference_1  | *** uWSGI is running in multiple interpreter mode ***
coreference_1  | spawned uWSGI master process (pid: 1)
coreference_1  | spawned uWSGI worker 1 (pid: 9, cores: 1)
coreference_1  | spawned uWSGI worker 2 (pid: 11, cores: 1)
coreference_1  | spawned uWSGI worker 3 (pid: 12, cores: 1)
coreference_1  | spawned uWSGI worker 4 (pid: 15, cores: 1)
graphene_1     | Exception in thread "main" com.typesafe.config.ConfigException$IO: /usr/share/graphene/conf/graphene.conf: java.io.FileNotFoundException: /usr/share/graphene/conf/graphene.conf (No such file or directory)
graphene_1     |        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:188)
graphene_1     |        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
graphene_1     |        at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
graphene_1     |        at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:688)
graphene_1     |        at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:51)
graphene_1     |        at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:473)
graphene_1     |        at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:259)
graphene_1     |        at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:256)
graphene_1     |        at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:65)
graphene_1     |        at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:92)
graphene_1     |        at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:256)
graphene_1     |        at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:232)
graphene_1     |        at org.lambda3.graphene.server.GrapheneRESTServer.<init>(GrapheneRESTServer.java:50)
graphene_1     |        at org.lambda3.graphene.server.GrapheneServer.main(GrapheneServer.java:33)
graphene_1     | Caused by: java.io.FileNotFoundException: /usr/share/graphene/conf/graphene.conf (No such file or directory)
graphene_1     |        at java.io.FileInputStream.open0(Native Method)
graphene_1     |        at java.io.FileInputStream.open(FileInputStream.java:195)
graphene_1     |        at java.io.FileInputStream.<init>(FileInputStream.java:138)
graphene_1     |        at com.typesafe.config.impl.Parseable$ParseableFile.reader(Parseable.java:638)
graphene_1     |        at com.typesafe.config.impl.Parseable.reader(Parseable.java:99)
graphene_1     |        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:231)
graphene_1     |        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
graphene_1     |        ... 13 more
graphene_graphene_1 exited with code 1
```

**Comment by Mischn** [comment]
Just place an empty `graphene.conf` file inside the `conf` directory:
`touch conf/graphene.conf`

I have added this remark to the README.md.

**Comment by wnunderwood** [comment]
Thanks

**Comment by mithrial** [comment]
Additionally, if you are only using Graphene-Core as a library, you must have a in your classpath (best put in `src/main/resources/application.conf`)
