### ISSUE TITLE
Cannot start service graphene: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"bin/start.sh\": stat bin/start.sh: no such file or directory": unknown

### ISSUE THREAD

**Issue by tonyywang** [Lambda-3/Graphene#23]
Hello, we're a group of students interested in using Graphene for a school project :)

When attempting to run docker-compose up to use the graphene server, I get the following error:

`ERROR: for graphene  Cannot start service graphene: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"bin/start.sh\": stat bin/start.sh: no such file or directory": unknown`

We are not sure why this happens on some environments but not others. We have successfully installed the graphene server on one computer, but it is failing on two more systems. (Successful system is OSX El Capitan; unsuccessful on OSX High Sierra and Windows machines.)

relevant `docker-compose --verbose up` output is as below:

```
compose.parallel.feed_queue: Pending: {<Service: corenlp>, <Service: coreference>, <Service: graphene>}
compose.parallel.feed_queue: Starting producer thread for <Service: corenlp>
compose.service.execute_convergence_plan: graphene_corenlp_1 is up-to-date
compose.parallel.parallel_execute_iter: Finished processing: <Service: corenlp>
compose.parallel.feed_queue: Pending: {<Service: coreference>, <Service: graphene>}
compose.parallel.feed_queue: Starting producer thread for <Service: coreference>
compose.service.execute_convergence_plan: graphene_coreference_1 is up-to-date
compose.parallel.parallel_execute_iter: Finished processing: <Service: coreference>
compose.parallel.feed_queue: Pending: {<Service: graphene>}
compose.parallel.feed_queue: Starting producer thread for <Service: graphene>
Starting graphene_graphene_1 ... 
compose.parallel.feed_queue: Pending: {<Container: graphene_graphene_1 (a14a65)>}
compose.parallel.feed_queue: Starting producer thread for <Container: graphene_graphene_1 (a14a65)>
compose.cli.verbose_proxy.proxy_callable: docker attach <- ('a14a654b0d9e6d8c41dab64a39af4af8b5070c9463203b9c5ed3d0870ebcd008', stdout=True, stderr=True, stream=True)
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.25/containers/a14a654b0d9e6d8c41dab64a39af4af8b5070c9463203b9c5ed3d0870ebcd008/attach?logs=0&stdout=1&stderr=1&stream=1 HTTP/1.1" 101 0
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.25/containers/a14a654b0d9e6d8c41dab64a39af4af8b5070c9463203b9c5ed3d0870ebcd008/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker attach -> <generator object frames_iter at 0x11019b830>
compose.cli.verbose_proxy.proxy_callable: docker start <- ('a14a654b0d9e6d8c41dab64a39af4af8b5070c9463203b9c5ed3d0870ebcd008')
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.25/containers/a14a654b0d9e6d8c41dab64a39af4af8b5070c9463203b9c5ed3d0870ebcd008/start HTTP/1.1" 400 185
Starting graphene_graphene_1 ... error
compose.parallel.feed_queue: Pending: set()

ERROR: for graphene_graphene_1  Cannot start service graphene: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"bin/start.sh\": stat bin/start.sh: no such file or directory": unknown
compose.parallel.parallel_execute_iter: Failed: <Service: graphene>
compose.parallel.feed_queue: Pending: set()

ERROR: for graphene  Cannot start service graphene: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"bin/start.sh\": stat bin/start.sh: no such file or directory": unknown
ERROR: compose.cli.main.main: Encountered errors while bringing up the project.
```

Please let me know if you might need any other info.

**Comment by bermeitinger-b** [comment]
Hi, 
everybody starts with something eventually.

You are right, in this case, it is a simple mistake. With docker, you can give different labels to the images. By default, docker automatically uses the label `:latest` if you don't add one. 
For this image, I didn't push the latest tag but only `:3.0.0-SNAPSHOT`.

**Comment by tonyywang** [comment]
Thanks for explaining!

Two things: I used ```git clone -b docker_workaround``` and simply ```docker-compose up``` on your finished image file. It starts the server but for some reason the graphene container exists, so it is not possible to use it. Code for this problem can be found below:

```
graphene_1     | Exception in thread "main" com.typesafe.config.ConfigException$IO: /usr/share/graphene/conf/graphene.conf: java.io.FileNotFoundException: /usr/share/graphene/conf/graphene.conf (No such file or directory)
graphene_1     | 	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:188)
graphene_1     | 	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
graphene_1     | 	at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
graphene_1     | 	at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:688)
graphene_1     | 	at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:51)
graphene_1     | 	at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:473)
graphene_1     | 	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:259)
graphene_1     | 	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:256)
graphene_1     | 	at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:65)
graphene_1     | 	at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:92)
graphene_1     | 	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:256)
graphene_1     | 	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:232)
graphene_1     | 	at org.lambda3.graphene.server.GrapheneRESTServer.<init>(GrapheneRESTServer.java:50)
graphene_1     | 	at org.lambda3.graphene.server.GrapheneServer.main(GrapheneServer.java:35)
graphene_1     | Caused by: java.io.FileNotFoundException: /usr/share/graphene/conf/graphene.conf (No such file or directory)
graphene_1     | 	at java.io.FileInputStream.open0(Native Method)
graphene_1     | 	at java.io.FileInputStream.open(FileInputStream.java:195)
graphene_1     | 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
graphene_1     | 	at com.typesafe.config.impl.Parseable$ParseableFile.reader(Parseable.java:638)
graphene_1     | 	at com.typesafe.config.impl.Parseable.reader(Parseable.java:99)
graphene_1     | 	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:231)
graphene_1     | 	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
graphene_1     | 	... 13 more
graphene_graphene_1 exited with code 1
```

After doing a ton of debugging we believe the main cause of this may be issues with user permissions.

After changing the .dockerignore file from the default 

```
**/*.*
!graphene-server/target/graphene*
```

to the following

```
**/*.*
!graphene-server/target/graphene-*-dist/**/*.*
```
everything seems to be running fine.

Judging on the error from your docker_workaround branch, it seems like permissions may also be cause the error with ```/usr/share/graphene/``` folder. Hope this helps!

**Comment by bermeitinger-b** [comment]
Thanks for your investigation.

It is complaining about the missing config file. If you look at the docker compose file, the conf directory is mounted into the container. You should create the graphene.conf and adjust  your settings.
This should be in the readme.

**Comment by tonyywang** [comment]
Hello,

Yes, with the finished docker image you uploaded, adding in the config file worked perfectly fine. I've installed and reinstalled Graphene several times so I didn't realize I was missing that from this installation.

Great, both your work around and our change to the dockerignore file seem to be working fine, and we will continue to use your workaround for now to make it easier to install.

Thanks a lot for the help!
